# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI build
on:
  push:
    branches:
      - main1
env:
  PATH_TO_SOLUTION: MySampleWebApp/MySampleWebApp.sln

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
  
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        include-prerelease: false
        
        
  build:
    runs-on: ubuntu-latest
    environment: 'production'
    needs: setup
    steps:
    
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: Build with dotnet
      run: dotnet build ${{ env.PATH_TO_SOLUTION }} --configuration Release
